services:
   web:
    build: .
    command:  >
      sh -c "python manage.py migrate --settings=api.test &&
             python manage.py makemigrations example --settings=api.test &&
             python manage.py migrate example --settings=api.test &&
             python manage.py runserver 0.0.0.0:8000 --settings=api.test"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network

   db:
    image: postgres:13.15-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER_DOCKER}
      POSTGRES_PASSWORD: ${PG_PASSWORD_DOCKER}
      POSTGRES_DB: ${PG_NAME_DOCKER}
    ports:
      - "5433:5432"
    networks:
      - my_network
   
  

networks:
  my_network:
    driver: bridge