# Generated by Django 4.1.3 on 2024-11-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('turma', models.CharField(max_length=20)),
                ('bolsa_familia', models.BooleanField()),
                ('sexo', models.CharField(max_length=20)),
                ('ativo', models.BooleanField()),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
    ]
