# Generated by Django 4.1.3 on 2024-11-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunomodel',
            name='alcool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='alunomodel',
            name='jogos',
            field=models.BooleanField(default=0),
        ),
    ]
